services:
  ds4:
    # controller
    image: brean/ds4-ros2:jazzy_001
    build:
      context: ./ds4/
      dockerfile: ./Dockerfile
      args:
        - ROS_DISTRO=jazzy
    privileged: True
    environment:
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
    volumes:
      - /dev:/dev
    network_mode: host

  cmd_vel:
    # output of cmd_vel
    build:
      args:
        - ROS_DISTRO=jazzy
      context: ./cmd_vel/
      dockerfile: ./Dockerfile
    environment:
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
    network_mode: host