services:
  ds4:
    # controller
    image: brean/ds4-ros2:jazzy_001
    build:
      context: ./ds4/
      dockerfile: ./Dockerfile
      args:
        - ROS_DISTRO=jazzy
    privileged: True
    volumes:
      - /dev:/dev

  cmd_vel:
    # output of cmd_vel
    build:
      args:
        - ROS_DISTRO=jazzy
      context: ./cmd_vel/
      dockerfile: ./Dockerfile
